env:
  es2021: true
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
ignorePatterns:
  - vite.config.js
  - vite.config.ts

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - filename-rules
rules:
  react/jsx-filename-extension: ['warn', extensions: [.jsx, .tsx]]
  react/react-in-jsx-scope: 'off'
  filename-rules/match: ['error', { .tsx: PascalCase, .ts: camelCase }]
  'react/prop-types': 'off'
  '@typescript-eslint/consistent-type-imports': 'off'
  '@typescript-eslint/naming-convention':
    [
      'error',
      { 'selector': ['class', 'interface', 'typeAlias'], 'format': ['PascalCase'] },
      { 'selector': ['property'], 'format': ['camelCase'], 'leadingUnderscore': 'allow' },
      {
        'selector': ['property'],
        'modifiers': ['readonly'],
        'format': ['camelCase', 'UPPER_CASE'],
        'leadingUnderscore': 'allow',
      },
      { 'selector': ['objectLiteralProperty'], 'format': ['UPPER_CASE', 'camelCase'], 'leadingUnderscore': 'allow' },
      { 'selector': ['parameterProperty'], 'format': ['camelCase'], 'leadingUnderscore': 'allow' },
      { 'selector': 'variable', 'format': ['camelCase'], 'leadingUnderscore': 'allow' },
      {
        'selector': ['variable'],
        'modifiers': ['const'],
        'format': ['camelCase', 'UPPER_CASE'],
        'leadingUnderscore': 'allow',
      },
      { 'selector': ['method', 'function'], 'format': ['camelCase'] },
    ]
  '@typescript-eslint/explicit-member-accessibility': 'warn'
overrides:
  - files: '*.d.ts'
    rules:
      filename-rules/match: ['error', 'kebab-case']
  # インタフェースは'IHogehoge.ts'なので例外
  - files: 'I*.ts'
    rules:
      filename-rules/match: ['error', 'PascalCase']
  - files: '*.tsx'
    rules:
      '@typescript-eslint/naming-convention':
        - 'error'
        - { 'selector': 'variable', 'format': ['camelCase', 'UPPER_CASE', 'PascalCase'], 'leadingUnderscore': 'allow' }
settings:
  react:
    version: 'detect'
    'import/resolver': { typescript: {} }
